DELETE FROM painelexames.LANCAMENTOS;

/**********/
/*EXAME 01*/
/**********/

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 1 AS CD_EXAME, TO_CHAR(SYSDATE,'DD/MM/YY') AS DT_EXAME, '10' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 1 AS CD_EXAME, TO_CHAR(SYSDATE+2,'DD/MM/YY') AS DT_EXAME, '5' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 1 AS CD_EXAME, TO_CHAR(SYSDATE+4,'DD/MM/YY') AS DT_EXAME, '15' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 1 AS CD_EXAME, TO_CHAR(SYSDATE+5,'DD/MM/YY') AS DT_EXAME, '21' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

/**********/
/*EXAME 02*/
/**********/

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 2 AS CD_EXAME, TO_CHAR(SYSDATE,'DD/MM/YY') AS DT_EXAME, '10' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 2 AS CD_EXAME, TO_CHAR(SYSDATE+2,'DD/MM/YY') AS DT_EXAME, '12' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 2 AS CD_EXAME, TO_CHAR(SYSDATE+4,'DD/MM/YY') AS DT_EXAME, '13' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 2 AS CD_EXAME, TO_CHAR(SYSDATE+5,'DD/MM/YY') AS DT_EXAME, '22' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

/**********/
/*EXAME 02*/
/**********/

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 2 AS CD_EXAME, TO_CHAR(SYSDATE,'DD/MM/YY') AS DT_EXAME, '1' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 2 AS CD_EXAME, TO_CHAR(SYSDATE+1,'DD/MM/YY') AS DT_EXAME, '12' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 3 AS CD_EXAME, TO_CHAR(SYSDATE+5,'DD/MM/YY') AS DT_EXAME, '2' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
467738 AS PACIENTE, 3 AS CD_EXAME, TO_CHAR(SYSDATE+7,'DD/MM/YY') AS DT_EXAME, '21' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, SYSDATE AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

COMMIT;

SELECT *
FROM painelexames.LANCAMENTOS lanc
WHERE lanc.CD_PACIENTE = 467738;
