/*************/
/*LANCAMENTOS*/
/*************/

DROP TABLE painelexames.LANCAMENTOS;

CREATE TABLE painelexames.LANCAMENTOS (
  CD_LANCAMENTO INT NOT NULL,
  CD_PACIENTE INT NOT NULL,
  CD_EXAME INT NOT NULL,
  DT_EXAME DATE NOT NULL,
  VL_LANCAMENTO NVARCHAR2(20) NOT NULL,
  CD_USUARIO_CRIACAO VARCHAR2(30) NOT NULL,
  HR_CRIACAO TIMESTAMP NOT NULL,
  CD_USUARIO_ULTIMA_ALTERACAO VARCHAR2(30) NULL,
  HR_ULTIMA_ALTERACAO TIMESTAMP NULL
);

--SEQUENCE
DROP SEQUENCE painelexames.SEQ_CD_LANCAMENTO;

CREATE SEQUENCE painelexames.SEQ_CD_LANCAMENTO  
MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 
START WITH 1;

--COMENTARIOS
COMMENT ON COLUMN lancamentos.CD_LANCAMENTO 
IS 'SEQ_CD_LANCAMENTO';

/*****/
/*LOG*/
/*****/

DROP TABLE painelexames.LOG_LANCAMENTOS;

CREATE TABLE painelexames.LOG_LANCAMENTOS (
  CD_LOG_LANCAMENTO INT NOT NULL,
  CD_PACIENTE INT NOT NULL,
  CD_EXAME INT NOT NULL,
  DT_EXAME DATE NOT NULL,
  VL_LANCAMENTO NVARCHAR2(20) NOT NULL,
  CD_USUARIO_CRIACAO VARCHAR2(30) NOT NULL,
  HR_CRIACAO TIMESTAMP NOT NULL,
  CD_USUARIO_ULTIMA_ALTERACAO VARCHAR2(30) NULL,
  HR_ULTIMA_ALTERACAO TIMESTAMP NULL,
  --INFORMACOES LOG
  TP_ALTERACAO VARCHAR(1), --(I) INSERT / (U) UPDATE / (D) DELETE
  TP_UPDATE VARCHAR(1), --(A) ANTES / (D) DEPOIS
  HR_LOG TIMESTAMP,
  CD_USUARIO_DB_LOG VARCHAR(30) NOT NULL
);

--SEQUENCE
DROP SEQUENCE painelexames.SEQ_CD_LOG_LANCAMENTO;

CREATE SEQUENCE painelexames.SEQ_CD_LOG_LANCAMENTO 
MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 
START WITH 1;

--COMENTARIOS
COMMENT ON COLUMN log_lancamentos.CD_LOG_LANCAMENTO
IS 'SEQ_CD_LOG_LANCAMENTO';

/*************/
/*TRIGGER LOG*/
/*************/

CREATE OR REPLACE TRIGGER TRG_LOG_LANCAMENTOS
BEFORE UPDATE OR INSERT OR DELETE
ON painelexames.LANCAMENTOS
REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN

   IF Inserting THEN

     --INSERT
     INSERT INTO painelexames.LOG_LANCAMENTOS
     SELECT SEQ_CD_LOG_LANCAMENTO.NEXTVAL,
     :new.CD_PACIENTE, :new.CD_EXAME, :new.DT_EXAME, :new.VL_LANCAMENTO,
     -- CAMPOS PADRAO
     :new.CD_USUARIO_CRIACAO,:new.HR_CRIACAO,:new.CD_USUARIO_ULTIMA_ALTERACAO,:new.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'I' AS TP_ALTERACAO, NULL TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

   ELSIF Updating THEN

     --UPDATE (ANTES)
     INSERT INTO painelexames.LOG_LANCAMENTOS
     SELECT SEQ_CD_LOG_LANCAMENTO.NEXTVAL, 
     :old.CD_PACIENTE, :old.CD_EXAME, :old.DT_EXAME, :old.VL_LANCAMENTO,
     -- CAMPOS PADRAO
     :old.CD_USUARIO_CRIACAO,:old.HR_CRIACAO,:old.CD_USUARIO_ULTIMA_ALTERACAO,:old.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'U' AS TP_ALTERACAO, 'A' TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

     --UPDATE (DEPOIS)
     INSERT INTO painelexames.LOG_LANCAMENTOS
     SELECT SEQ_CD_LOG_LANCAMENTO.NEXTVAL,
     :new.CD_PACIENTE, :new.CD_EXAME, :new.DT_EXAME, :new.VL_LANCAMENTO,
     -- CAMPOS PADRAO
     :new.CD_USUARIO_CRIACAO,:new.HR_CRIACAO,:new.CD_USUARIO_ULTIMA_ALTERACAO,:new.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'U' AS TP_ALTERACAO, 'D' TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

   ELSIF Deleting THEN

     --DELETE
     INSERT INTO painelexames.LOG_LANCAMENTOS
     SELECT SEQ_CD_LOG_LANCAMENTO.NEXTVAL, 
     :old.CD_PACIENTE, :old.CD_EXAME, :old.DT_EXAME, :old.VL_LANCAMENTO,
     --CAMPOS PADRAO
     :old.CD_USUARIO_CRIACAO,:old.HR_CRIACAO,:old.CD_USUARIO_ULTIMA_ALTERACAO,:old.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'D' AS TP_ALTERACAO, NULL TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

   END IF;

END;
/

/***********/
/*VALIDACAO*/
/***********/

----------
--INSERT--
----------

INSERT INTO painelexames.LANCAMENTOS
SELECT painelexames.SEQ_CD_LANCAMENTO.NEXTVAL AS CD_LANCAMENTO,
123 AS PACIENTE, 1 AS CD_EXAME, TO_CHAR(SYSDATE,'DD/MM/YY') AS DT_EXAME, '10' AS VL_LANCAMENTO,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO, '27/02/2021' AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

COMMIT;

--VALIDA
SELECT *
FROM painelexames.LANCAMENTOS m;

--VALIDA LOG
SELECT *
FROM painelexames.LOG_LANCAMENTOS m
WHERE m.TP_ALTERACAO = 'I';

----------
--UPDATE--
----------

UPDATE painelexames.LANCAMENTOS m
SET m.VL_LANCAMENTO = '11'
WHERE M.CD_LANCAMENTO = 1;

COMMIT;

--VALIDA
SELECT *
FROM painelexames.LANCAMENTOS m;

--VALIDA LOG
SELECT *
FROM painelexames.LOG_LANCAMENTOS m
WHERE m.TP_ALTERACAO = 'U';

----------
--DELETE--
----------

DELETE 
FROM painelexames.LANCAMENTOS m
WHERE m.CD_LANCAMENTO = 1;

COMMIT;

--VALIDA
SELECT *
FROM painelexames.LANCAMENTOS m;

--VALIDA LOG
SELECT *
FROM painelexames.LOG_LANCAMENTOS m
WHERE m.TP_ALTERACAO = 'D';
