SELECT atd.CD_PACIENTE, pdl.DT_EXAME, re.CD_EXA_LAB, exl.NM_EXA_LAB, re.DS_RESULTADO
FROM dbamv.ATENDIME atd
INNER JOIN dbamv.PED_LAB pdl
  ON pdl.CD_ATENDIMENTO = atd.CD_ATENDIMENTO
INNER JOIN dbamv.RES_EXA re
  ON re.CD_PED_LAB = pdl.CD_PED_LAB
INNER JOIN dbamv.EXA_LAB exl
  ON exl.CD_EXA_LAB = re.CD_EXA_LAB
WHERE atd.CD_PACIENTE = 467738
AND re.CD_EXA_LAB IN (1829)
