SELECT *
FROM ALL_TAB_COLUMNS atc
WHERE atc.COLUMN_NAME LIKE '%SINAL_VITAL%'

SELECT * FROM SINAL_VITAL;
SELECT * FROM COLETA_SINAL_VITAL WHERE CD_ATENDIMENTO IS NOT NULL ORDER BY 4 DESC;
SELECT * FROM ITCOLETA_SINAL_VITAL;


SELECT *
FROM dbamv.COLETA_SINAL_VITAL csv
INNER JOIN dbamv.ITCOLETA_SINAL_VITAL itcsv
  ON itcsv.CD_COLETA_SINAL_VITAL = csv.CD_COLETA_SINAL_VITAL
INNER JOIN dbamv.SINAL_VITAL sv
  ON sv.CD_SINAL_VITAL = itcsv.CD_SINAL_VITAL
WHERE csv.CD_ATENDIMENTO = 4170361


