/*************/
/*LANCAMENTOS*/
/*************/

DROP TABLE painelexames.DOADORES;

CREATE TABLE painelexames.DOADORES (
  CD_DOADOR INT NOT NULL,
  CD_PACIENTE INT NOT NULL,
  DT_TRANSPLANTE DATE NOT NULL,
  ESQ_FRIA NVARCHAR2(50) NOT NULL,
  ESQ_MORNA NVARCHAR2(50) NOT NULL,
  ESQ_TOTAL NVARCHAR2(50) NOT NULL,
  ESQ_FASE NVARCHAR2(50) NOT NULL,
  IDADE INT NOT NULL,
  PESO NVARCHAR2(50) NOT NULL,
  CAUSA_OBITO NVARCHAR2(50) NOT NULL,
  TIPO_SANGUE NVARCHAR2(50) NOT NULL,
  CMV NVARCHAR2(50) NOT NULL,
  SOROL_HEPAT NVARCHAR2(50) NOT NULL,
  ENZ_HEPAT NVARCHAR2(50) NOT NULL,
  TIPO_SANGUINEO NVARCHAR2(50) NOT NULL,
  CIR_PREVIA NVARCHAR2(50) NOT NULL,
  MELD_INT NVARCHAR2(50) NOT NULL,
  T_CIRURGIA NVARCHAR2(50) NOT NULL,
  TRANSFUSAO NVARCHAR2(50) NOT NULL,
  --PADRAO
  CD_USUARIO_CRIACAO VARCHAR2(30) NOT NULL,
  HR_CRIACAO TIMESTAMP NOT NULL,
  CD_USUARIO_ULTIMA_ALTERACAO VARCHAR2(30) NULL,
  HR_ULTIMA_ALTERACAO TIMESTAMP NULL
);

--SEQUENCE
DROP SEQUENCE painelexames.SEQ_CD_DOADOR;

CREATE SEQUENCE painelexames.SEQ_CD_DOADOR  
MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 
START WITH 1;

--COMENTARIOS
COMMENT ON COLUMN doadores.CD_DOADOR 
IS 'SEQ_CD_DOADOR';

/*****/
/*LOG*/
/*****/

DROP TABLE painelexames.LOG_DOADORES;

CREATE TABLE painelexames.LOG_DOADORES(
  CD_LOG_DOADOR INT NOT NULL,
  CD_PACIENTE INT NOT NULL,
  DT_TRANSPLANTE DATE NOT NULL,
  ESQ_FRIA NVARCHAR2(50) NOT NULL,
  ESQ_MORNA NVARCHAR2(50) NOT NULL,
  ESQ_TOTAL NVARCHAR2(50) NOT NULL,
  ESQ_FASE NVARCHAR2(50) NOT NULL,
  IDADE INT NOT NULL,
  PESO NVARCHAR2(50) NOT NULL,
  CAUSA_OBITO NVARCHAR2(50) NOT NULL,
  TIPO_SANGUE NVARCHAR2(50) NOT NULL,
  CMV NVARCHAR2(50) NOT NULL,
  SOROL_HEPAT NVARCHAR2(50) NOT NULL,
  ENZ_HEPAT NVARCHAR2(50) NOT NULL,
  TIPO_SANGUINEO NVARCHAR2(50) NOT NULL,
  CIR_PREVIA NVARCHAR2(50) NOT NULL,
  MELD_INT NVARCHAR2(50) NOT NULL,
  T_CIRURGIA NVARCHAR2(50) NOT NULL,
  TRANSFUSAO NVARCHAR2(50) NOT NULL, 
  --PADRAO
  CD_USUARIO_CRIACAO VARCHAR2(30) NOT NULL,
  HR_CRIACAO TIMESTAMP NOT NULL,
  CD_USUARIO_ULTIMA_ALTERACAO VARCHAR2(30) NULL,
  HR_ULTIMA_ALTERACAO TIMESTAMP NULL,
  --INFORMACOES LOG
  TP_ALTERACAO VARCHAR(1), --(I) INSERT / (U) UPDATE / (D) DELETE
  TP_UPDATE VARCHAR(1), --(A) ANTES / (D) DEPOIS
  HR_LOG TIMESTAMP,
  CD_USUARIO_DB_LOG VARCHAR(30) NOT NULL
);

--SEQUENCE
DROP SEQUENCE painelexames.SEQ_CD_LOG_DOADOR;

CREATE SEQUENCE painelexames.SEQ_CD_LOG_DOADOR
MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 
START WITH 1;

--COMENTARIOS
COMMENT ON COLUMN log_doadores.CD_LOG_DOADOR
IS 'SEQ_CD_LOG_DOADOR';

/*************/
/*TRIGGER LOG*/
/*************/

CREATE OR REPLACE TRIGGER TRG_LOG_DOADORES
BEFORE UPDATE OR INSERT OR DELETE
ON painelexames.DOADORES
REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN

   IF Inserting THEN

     --INSERT
     INSERT INTO painelexames.LOG_DOADORES
     SELECT SEQ_CD_LOG_DOADOR.NEXTVAL,
     :new.CD_PACIENTE, :new.DT_TRANSPLANTE, :new.ESQ_FRIA,
     :new.ESQ_MORNA, :new.ESQ_TOTAL, :new.ESQ_FASE, :new.IDADE, :new.PESO,
     :new.CAUSA_OBITO, :new.TIPO_SANGUE, :new.CMV, :new.SOROL_HEPAT,
     :new.ENZ_HEPAT, :new.TIPO_SANGUINEO, :new.CIR_PREVIA,
     :new.MELD_INT, :new.T_CIRURGIA, :new.TRANSFUSAO,
     -- CAMPOS PADRAO
     :new.CD_USUARIO_CRIACAO,:new.HR_CRIACAO,:new.CD_USUARIO_ULTIMA_ALTERACAO,:new.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'I' AS TP_ALTERACAO, NULL TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

   ELSIF Updating THEN

     --UPDATE (ANTES)
     INSERT INTO painelexames.LOG_DOADORES
     SELECT SEQ_CD_LOG_DOADOR.NEXTVAL, 
     :old.CD_PACIENTE, :old.DT_TRANSPLANTE, :old.ESQ_FRIA,
     :old.ESQ_MORNA, :old.ESQ_TOTAL, :old.ESQ_FASE, :old.IDADE, :old.PESO,
     :old.CAUSA_OBITO, :old.TIPO_SANGUE, :old.CMV, :old.SOROL_HEPAT,
     :old.ENZ_HEPAT, :old.TIPO_SANGUINEO, :old.CIR_PREVIA,
     :old.MELD_INT, :old.T_CIRURGIA, :old.TRANSFUSAO,
     -- CAMPOS PADRAO
     :old.CD_USUARIO_CRIACAO,:old.HR_CRIACAO,:old.CD_USUARIO_ULTIMA_ALTERACAO,:old.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'U' AS TP_ALTERACAO, 'A' TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

     --UPDATE (DEPOIS)
     INSERT INTO painelexames.LOG_DOADORES
     SELECT SEQ_CD_LOG_DOADOR.NEXTVAL,
     :new.CD_PACIENTE, :new.DT_TRANSPLANTE, :new.ESQ_FRIA,
     :new.ESQ_MORNA, :new.ESQ_TOTAL, :new.ESQ_FASE, :new.IDADE, :new.PESO,
     :new.CAUSA_OBITO, :new.TIPO_SANGUE, :new.CMV, :new.SOROL_HEPAT,
     :new.ENZ_HEPAT, :new.TIPO_SANGUINEO, :new.CIR_PREVIA,
     :new.MELD_INT, :new.T_CIRURGIA, :new.TRANSFUSAO,
     -- CAMPOS PADRAO
     :new.CD_USUARIO_CRIACAO,:new.HR_CRIACAO,:new.CD_USUARIO_ULTIMA_ALTERACAO,:new.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'U' AS TP_ALTERACAO, 'D' TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

   ELSIF Deleting THEN

     --DELETE
     INSERT INTO painelexames.LOG_DOADORES
     SELECT SEQ_CD_LOG_DOADOR.NEXTVAL, 
     :old.CD_PACIENTE, :old.DT_TRANSPLANTE, :old.ESQ_FRIA,
     :old.ESQ_MORNA, :old.ESQ_TOTAL, :old.ESQ_FASE, :old.IDADE, :old.PESO,
     :old.CAUSA_OBITO, :old.TIPO_SANGUE, :old.CMV, :old.SOROL_HEPAT,
     :old.ENZ_HEPAT, :old.TIPO_SANGUINEO, :old.CIR_PREVIA,
     :old.MELD_INT, :old.T_CIRURGIA, :old.TRANSFUSAO,
     --CAMPOS PADRAO
     :old.CD_USUARIO_CRIACAO,:old.HR_CRIACAO,:old.CD_USUARIO_ULTIMA_ALTERACAO,:old.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'D' AS TP_ALTERACAO, NULL TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

   END IF;

END;
/

/***********/
/*VALIDACAO*/
/***********/

----------
--INSERT--
----------

INSERT INTO painelexames.DOADORES
SELECT painelexames.SEQ_CD_DOADOR.NEXTVAL AS CD_DOADOR,
123456 AS CD_PACIENTE, '26/07/2021' AS DT_TRANSPLANTE, '27t' ESQ_FRIA,
'22t' AS ESQ_MORNA, '49t' AS ESQ_TOTAL, 'Monofase' AS ESQ_FASE, 5 AS IDADE, '77,8' AS PESO,
'Morte morrida' AS CAUSA_OBITO, 'Ab+' AS TIPO_SANGUE, 'Positivo' AS CMV, 'Soro' AS SOROL_HEPAT,
'Enziema' AS ENZ_HEPAT, 'Vermelho' AS TIPO_SANGUINEO, 'Faz Tempo' AS CIR_PREVIA,
'Menta' AS MELD_INT, 'Demorado' AS T_CIRURGIA, 'Transferência de sangue de um paciente para outro' AS TRANSFUSAO,
--PADRAO
'HSSAMPAIO' AS CD_USUARIO_CRIACAO, '27/02/2021' AS HR_CRIACAO,
NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

COMMIT;

--VALIDA
SELECT *
FROM painelexames.DOADORES m;

--VALIDA LOG
SELECT *
FROM painelexames.LOG_DOADORES m
WHERE m.TP_ALTERACAO = 'I';

----------
--UPDATE--
----------

UPDATE painelexames.DOADORES m
SET m.IDADE = 35
WHERE M.CD_DOADOR = 1;

COMMIT;

--VALIDA
SELECT *
FROM painelexames.DOADORES m;

--VALIDA LOG
SELECT *
FROM painelexames.LOG_DOADORES m
WHERE m.TP_ALTERACAO = 'U';

----------
--DELETE--
----------

DELETE 
FROM painelexames.DOADORES m
WHERE m.CD_DOADOR = 1;

COMMIT;

--VALIDA
SELECT *
FROM painelexames.DOADORES m;

--VALIDA LOG
SELECT *
FROM painelexames.LOG_DOADORES m
WHERE m.TP_ALTERACAO = 'D';
