/******/
/*EXAME*/
/******/

DROP TABLE painelexames.EXAMES;

CREATE TABLE painelexames.EXAMES (
  CD_EXAME INT NOT NULL,
  ORDENACAO INT NOT NULL,
  TP_EXAME VARCHAR2(1) NOT NULL,
  DS_EXAME VARCHAR2(45) NOT NULL,
  SN_MANUAL VARCHAR2(1) NULL,
  CD_EXA_LAB_MV INT NULL,
  CD_USUARIO_CRIACAO VARCHAR2(30) NOT NULL,
  HR_CRIACAO TIMESTAMP NOT NULL,
  CD_USUARIO_ULTIMA_ALTERACAO VARCHAR2(30) NULL,
  HR_ULTIMA_ALTERACAO TIMESTAMP NULL
);

--SEQUENCE
DROP SEQUENCE painelexames.SEQ_CD_EXAME;

CREATE SEQUENCE painelexames.SEQ_CD_EXAME  
MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 
START WITH 1;

--CONSTRAINTS
ALTER TABLE painelexames.EXAMES
ADD CONSTRAINT CK_EXAMES_SN_MANUAL
CHECK (SN_MANUAL IN ('S','N'));

ALTER TABLE painelexames.EXAMES
ADD CONSTRAINT CK_TP_EXAME
CHECK (TP_EXAME IN ('X','T'));

--COMENTARIOS
COMMENT ON COLUMN exames.CD_EXAME 
IS 'SEQ_CD_EXAME';

--COMENTARIOS
COMMENT ON COLUMN exames.TP_EXAME 
IS 'X - TX / T - TRANSPLANTE FIGADO';


/*****/
/*LOG*/
/*****/

DROP TABLE painelexames.LOG_EXAMES;

CREATE TABLE painelexames.LOG_EXAMES (
  CD_LOG_EXAME INT NOT NULL,
  ORDENACAO INT NOT NULL,
  TP_EXAME VARCHAR2(1) NOT NULL,
  DS_EXAME VARCHAR2(45) NOT NULL,
  SN_MANUAL VARCHAR2(1) NULL,
  CD_EXA_LAB_MV INT NULL,
  CD_USUARIO_CRIACAO VARCHAR2(30) NOT NULL,
  HR_CRIACAO TIMESTAMP NOT NULL,
  CD_USUARIO_ULTIMA_ALTERACAO VARCHAR2(30) NULL,
  HR_ULTIMA_ALTERACAO TIMESTAMP NULL,
   --INFORMACOES LOG
  TP_ALTERACAO VARCHAR(1), -- (I) INSERT / (U) UPDATE / (D) DELETE
  TP_UPDATE VARCHAR(1), -- (A) ANTES / (D) DEPOIS
  HR_LOG TIMESTAMP,
  CD_USUARIO_DB_LOG VARCHAR(30) NOT NULL
);

--SEQUENCE
DROP SEQUENCE painelexames.SEQ_CD_LOG_EXAME;

CREATE SEQUENCE painelexames.SEQ_CD_LOG_EXAME  
MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 
START WITH 1;

--CONSTRAINTS
ALTER TABLE painelexames.LOG_EXAMES
ADD CONSTRAINT CK_LOG_EXAMES_SN_MANUAL
CHECK (SN_MANUAL IN ('S','N'));

ALTER TABLE painelexames.LOG_EXAMES
ADD CONSTRAINT CK_LOG_TP_EXAME
CHECK (TP_EXAME IN ('X','T'));

--COMENTARIOS
COMMENT ON COLUMN log_exames.CD_LOG_EXAME 
IS 'SEQ_CD_LOG_EXAME';

COMMENT ON COLUMN log_exames.TP_EXAME 
IS 'X - TX / T - TRANSPLANTE FIGADO';

/*************/
/*TRIGGER LOG*/
/*************/

CREATE OR REPLACE TRIGGER TRG_LOG_EXAMES
BEFORE UPDATE OR INSERT OR DELETE
ON painelexames.EXAMES
REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN

   IF Inserting THEN

     --INSERT
     INSERT INTO painelexames.LOG_EXAMES
     SELECT SEQ_CD_LOG_EXAME.NEXTVAL,
     :new.ORDENACAO,:new.TP_EXAME,:new.DS_EXAME, :new.SN_MANUAL,:new.CD_EXA_LAB_MV,
     -- CAMPOS PADRAO
     :new.CD_USUARIO_CRIACAO,:new.HR_CRIACAO,:new.CD_USUARIO_ULTIMA_ALTERACAO,:new.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'I' AS TP_ALTERACAO, NULL TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

   ELSIF Updating THEN

     --UPDATE (ANTES)
     INSERT INTO painelexames.LOG_EXAMES
     SELECT SEQ_CD_LOG_EXAME.NEXTVAL, 
     :old.ORDENACAO, :old.TP_EXAME, :old.DS_EXAME, :old.SN_MANUAL,:new.CD_EXA_LAB_MV,
     -- CAMPOS PADRAO
     :old.CD_USUARIO_CRIACAO,:old.HR_CRIACAO,:old.CD_USUARIO_ULTIMA_ALTERACAO,:old.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'U' AS TP_ALTERACAO, 'A' TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

     --UPDATE (DEPOIS)
     INSERT INTO painelexames.LOG_EXAMES
     SELECT SEQ_CD_LOG_EXAME.NEXTVAL,
     :new.ORDENACAO,:new.TP_EXAME,:new.DS_EXAME, :new.SN_MANUAL,:new.CD_EXA_LAB_MV,
     -- CAMPOS PADRAO
     :new.CD_USUARIO_CRIACAO,:new.HR_CRIACAO,:new.CD_USUARIO_ULTIMA_ALTERACAO,:new.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'U' AS TP_ALTERACAO, 'D' TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

   ELSIF Deleting THEN

     --DELETE
     INSERT INTO painelexames.LOG_EXAMES
     SELECT SEQ_CD_LOG_EXAME.NEXTVAL, 
     :old.ORDENACAO, :old.TP_EXAME, :old.DS_EXAME, :old.SN_MANUAL,:new.CD_EXA_LAB_MV,
     --CAMPOS PADRAO
     :old.CD_USUARIO_CRIACAO,:old.HR_CRIACAO,:old.CD_USUARIO_ULTIMA_ALTERACAO,:old.HR_ULTIMA_ALTERACAO,
     --INFORMACOES LOG
     'D' AS TP_ALTERACAO, NULL TP_UPDATE, SYSTIMESTAMP AS HR_LOG, USER AS CD_USUARIO_DB_LOG
     FROM DUAL;

   END IF;

END;
/

/***********/
/*VALIDACAO*/
/***********/

----------
--INSERT--
----------

INSERT INTO painelexames.EXAMES
SELECT painelexames.SEQ_CD_EXAME.NEXTVAL AS CD_EXAME,
'1' AS ORDENACAO, 'X' AS TP_EXAME, 'THRX' AS DS_EXAME, 'N' AS SN_MANUAL, NULL AS CD_EXA_LAB_MV,
--PADRAO
'AVVMELO' AS CD_USUARIO_CRIACAO,
'27/02/2021' AS HR_CRIACAO, NULL AS CD_USUARIO_ULTIMA_ALTERACAO,NULL AS HR_ULTIMA_ALTERACAO
FROM DUAL;

COMMIT;

--VALIDA
SELECT *
FROM painelexames.EXAMES m;

--VALIDA LOG
SELECT *
FROM painelexames.LOG_EXAMES m
WHERE m.TP_ALTERACAO = 'I';

----------
--UPDATE--
----------

UPDATE painelexames.EXAMES m
SET m.SN_MANUAL = 'S'
WHERE M.CD_EXAME = 1;

COMMIT;

UPDATE painelexames.EXAMES m
SET m.SN_MANUAL = 'N'
WHERE M.CD_EXAME = 1;

COMMIT;

--VALIDA
SELECT *
FROM painelexames.EXAMES m;

--VALIDA LOG
SELECT *
FROM painelexames.LOG_EXAMES m
WHERE m.TP_ALTERACAO = 'U';

----------
--DELETE--
----------

DELETE 
FROM painelexames.EXAMES m
WHERE m.CD_EXAME = 2;

COMMIT;

--VALIDA
SELECT *
FROM painelexames.EXAMES m;

--VALIDA LOG
SELECT *
FROM painelexames.LOG_EXAMES m
WHERE m.TP_ALTERACAO = 'D';
