--RES_EXA PRECISA DE ITPED_LAB

SELECT re.*
FROM RES_EXA re;

--ITPED_LAB PRECISA DE PED_LAB

SELECT *
FROM PED_LAB pdl
INNER JOIN ITPED_LAB itpdl
  ON itpdl.CD_PED_LAB = pdl.CD_PED_LAB;
  
--PED_LAB PRECISA DE PRE_MED  
SELECT * FROM PED_LAB
